# Generated by Django 5.2.5 on 2026-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Whole naira per kilogram. Required for KG products; leave empty for fixed-price (unit) products.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_unit',
            field=models.CharField(choices=[('kg', 'Per kilogram (quantity × price per kg)'), ('unit', 'Fixed price (per variant)')], default='unit', help_text='kg: totals are quantity × price per kg. unit: fixed price from the product variant.', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text='Actual product option (e.g. bunch, basket, pack). Do not create one variant per KG quantity.', max_length=40),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(help_text='Fixed price in whole naira (₦) for this option.'),
        ),
    ]
