# Generated by Django 5.2.5 on 2026-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price_per_kg_product_pricing_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text="Auto-filled as '<product name> image' when left empty. You can still edit it for a better description.", max_length=125),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Whole naira per kilogram. Required for KG products. For fixed-price (unit) products set the price on the variant below instead — this value is only a display fallback.', null=True),
        ),
    ]
