# Generated by Django 5.2.5 on 2026-10-01 11:43

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_image_alt_alter_product_price_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'blog categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('author', models.CharField(default='Harvest Castle Team', max_length=80)),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated, e.g. tomatoes, storage, food waste.', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('image_alt', models.CharField(blank=True, default='', help_text="Auto-filled as '<title> image' when left empty. You can still edit it for a better description.", max_length=125)),
                ('image_caption', models.CharField(blank=True, default='', max_length=200)),
                ('body', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text="Editor's pick slot on the blog page.")),
                ('seo_title', models.CharField(blank=True, default='', max_length=160)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('reading_time', models.PositiveIntegerField(default=1, editable=False, help_text='Minutes, auto-calculated from the body (~250 wpm).')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='main.blogcategory')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='main_blogpo_status_40a3f1_idx')],
            },
        ),
    ]
