# Generated by Django 5.2.5 on 2026-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(help_text='Required — every post must have a featured image.', upload_to='blog/'),
        ),
    ]
