# Generated by Django 5.2.5 on 2026-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, default='Harvest Castle Team', max_length=80),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Short summary for search results (about 150–160 characters is ideal).', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Shown in browser tabs and search results. Leave empty to use the post title.', max_length=160),
        ),
    ]
